sonar.projectKey=rb-belarmino_AAW-GarageFlow
sonar.organization=rb-belarmino
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts,tests/**/*.tsx,**/*.test.ts,**/*.spec.ts
sonar.exclusions=node_modules/**,.next/**,prisma/**
sonar.cpd.exclusions=tests/**
